# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 20:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='add_weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AlterField(
            model_name='drone',
            name='speed',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AlterField(
            model_name='drone',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AlterField(
            model_name='route',
            name='load_weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
    ]
