# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 14:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_route_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 26, 16, 3, 35, 508746)),
        ),
    ]
