# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_auto_20161226_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
